import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { Layout } from '~/components/';
import Mousetrap from 'mousetrap';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();
  useEffect(() => {
    const log = () => {
      router.push('/');
    };
    Mousetrap.bind('ctrl+1', log);
    return () => Mousetrap.unbind('ctrl+1', log);
  }, [router]);

  useEffect(() => {
    const log = () => {
      router.push('/links');
    };
    Mousetrap.bind('ctrl+2', log);
    return () => Mousetrap.unbind('ctrl+2', log);
  }, [router]);

  useEffect(() => {
    const log = () => {
      console.log('K Bar baby');
    };
    Mousetrap.bind('mod+k', log);
    return () => Mousetrap.unbind('mod+k', log);
  }, [router]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>This is the main page</Layout>
    </div>
  );
};

export default Home;
